/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./components/**/*.tsx', './pages/**/*.tsx', './lib/**/*.tsx'],
  safelist: [
    'align-super',
    'bg-blue-500',
    'bg-blue-800',
    'bg-neutral-100',
    'bg-purple-100',
    'border-neutral-200',
    'border-t',
    'flex',
    'focus-visible:ring-opacity-75',
    'focus-visible:ring-purple-500',
    'focus-visible:ring',
    'focus:outline-none',
    'font-bold',
    'font-medium',
    'font-serif',
    'hover:bg-blue-300',
    'hover:bg-blue-700',
    'hover:bg-purple-200',
    'hover:cursor-default',
    'hover:cursor-pointer',
    'justify-between',
    'm-2',
    'mb-2',
    'px-3',
    'px-4',
    'py-2',
    'rounded-lg',
    'rounded',
    'text-amber-200',
    'text-amber-700',
    'text-left',
    'text-neutral-300',
    'text-purple-400',
    'text-purple-900',
    'text-xl',
    'text-sm',
    'text-white',
    'w-full',
  ],
  theme: {
    fontFamily: {
      'serif': ['Georgia', 'Times', 'Times New Roman', 'Cambria', 'ui-serif'],
    },
    extend: {
      colors: {
        'accent-1': '#FAFAFA',
        'accent-2': '#EAEAEA',
        'accent-7': '#333',
        success: '#0070f3',
        cyan: '#79FFE1',
      },
      spacing: {
        28: '7rem',
      },
      letterSpacing: {
        tighter: '-.04em',
      },
      lineHeight: {
        tight: 1.2,
      },
      fontSize: {
        '5xl': '2.5rem',
        '6xl': '2.75rem',
        '7xl': '4.5rem',
        '8xl': '6.25rem',
      },
      boxShadow: {
        sm: '0 5px 10px rgba(0, 0, 0, 0.12)',
        md: '0 8px 30px rgba(0, 0, 0, 0.12)',
      },
    },
  },
  plugins: [],
}
